packages:
  # - 'backups'
  - 'cernbox-integration'
  - 'codimd'
  - 'data-repositories'
  - 'draw-io'
  - 'ifc-js'
  # - 'image-editor'
  - 'jupyter'
  - 'lightweight-accounts'
  - 'ms-tracing'
  - 'ndmspc-reader'
  - 'old-web-redirector'
  - 'open-in-swan'
  - 'otg'
  - 'rootjs'
  - 'search-in-folder'
  - 'tours'

catalog:
  # @ownclouders tooling
  '@ownclouders/design-system': ^12.1.2
  '@ownclouders/eslint-config': ^12.1.2
  '@ownclouders/extension-sdk': ^12.1.2
  '@ownclouders/prettier-config': ^0.0.1
  '@ownclouders/tsconfig': ^0.0.6
  '@ownclouders/web-client': ^12.1.2
  '@ownclouders/web-pkg': ^12.1.2
  '@ownclouders/web-test-helpers': ^12.1.1

  # Build
  '@vitejs/plugin-vue': ^6.0.6
  vite: ^7.2.4

  # TypeScript / linting
  '@types/node': ^22.19.1
  eslint: ^9.39.1
  prettier: ^3.6.2
  typescript: ^5.9.3
  vue-tsc: ^2.1.10

  # Vue ecosystem
  '@vueuse/core': ^14.1.0
  pinia: ^3.0.4
  vue: ^3.5.25
  vue-router: ^4.4.5
  vue3-gettext: 4.0.0-beta.1
  vuex: ^4.1.0

  # CSS
  sass: ^1.81.0

  # Misc shared
  js-base64: ^3.7.7
  lodash-es: ^4.17.22
  qs: ^6.14.0
  rollup-plugin-node-polyfills: ^0.2.1
  vue-concurrency: ^5.0.1
